name: Get jar file
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build maven project
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
      
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: staging
